[package]
name = "wp-lottie-perf-test"
version = "1.0.0"
description = "WordPress Lottie Performance Test - Tipalti Finance AI Replica with 4 integration strategies"
license = "MIT"
readme = "README.md"

[[module]]
name = "wp-lottie-perf-test"
source = "."
abi = "wasi"

[module.interfaces]
wasi = "0.2.0"

[fs]
# Include all necessary files for the WordPress site
"/" = "."

[dependencies]

[command]
name = "serve"
module = "wp-lottie-perf-test"

# WordPress configuration - explicit detection
[package.metadata.wapm]
abi = "wasi"
# Explicitly mark as WordPress
runtime = "php"
framework = "wordpress"

# WordPress web server configuration
[package.metadata.web]
# WordPress entry point
index = "index.php"
# Explicitly set as PHP application
type = "php"

# WordPress-specific MIME types
[package.metadata.web.mime-types]
".php" = "application/x-httpd-php"
".html" = "text/html"
".css" = "text/css"
".js" = "application/javascript"
".mjs" = "application/javascript"
".json" = "application/json"
".lottie" = "application/json"
".svg" = "image/svg+xml"
".png" = "image/png"
".jpg" = "image/jpeg"
".jpeg" = "image/jpeg"
".webp" = "image/webp"
".gif" = "image/gif"
".ico" = "image/x-icon"
".woff" = "font/woff"
".woff2" = "font/woff2"
".ttf" = "font/ttf"
".eot" = "application/vnd.ms-fontobject"

# WordPress-specific headers
[package.metadata.web.headers]
# Cache static assets for 1 year
"wp-content/themes/*/assets/*" = { "Cache-Control" = "public, max-age=31536000, immutable" }
# Cache WordPress files appropriately
"wp-content/uploads/*" = { "Cache-Control" = "public, max-age=31536000" }
"wp-content/themes/*/*.css" = { "Cache-Control" = "public, max-age=86400" }
"wp-content/themes/*/*.js" = { "Cache-Control" = "public, max-age=86400" }
# Security headers for WordPress
"*" = { 
    "X-Content-Type-Options" = "nosniff",
    "X-Frame-Options" = "SAMEORIGIN",
    "X-XSS-Protection" = "1; mode=block",
    "Referrer-Policy" = "strict-origin-when-cross-origin"
}

# WordPress environment variables
[package.metadata.web.env]
WP_ENV = "production"
WP_DEBUG = "false"
WP_DEBUG_LOG = "false"
WP_DEBUG_DISPLAY = "false"
# WordPress database settings
DB_NAME = "wp_lottie_perf_test"
DB_USER = "wp_user"
DB_PASSWORD = "wp_password"
DB_HOST = "localhost"